from typing import Optional, Protocol
from core.models.models import Account


class IProxyChecker(Protocol):
    def check(self, proxy_url: str) -> tuple[bool, str]: ...


class IProxyParser(Protocol):
    def to_url(self, raw: str) -> Optional[str]: ...
    def to_playwright_dict(self, proxy_url: str) -> Optional[dict]: ...


class IBrowserFactory(Protocol):
    async def create(self, proxy_url: Optional[str]) -> tuple: ...


class ISessionManager(Protocol):
    async def login(self, page, account: Account) -> bool: ...
    async def is_logged_in(self, page) -> bool: ...
    async def ensure_logged_in(self, page, account: Account) -> bool: ...


class IMessageSender(Protocol):
    async def fill_text(self, page, text: str) -> bool: ...
    async def send_enter(self, page) -> None: ...


class ICloudflareWaiter(Protocol):
    async def wait(self, page, timeout: int) -> bool: ...